// Script Archetype Types
export type Archetype = 'Storytime' | 'Expert' | 'Savage' | 'Drama';
// Global type definitions

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Database types (will be generated by Supabase later)
export interface Database {
  // Add your database schema types here
}

// Shared application types
export interface User {
  id: string;
  email: string;
  createdAt: Date;
}

// API Response types
export interface ApiResponse<T = unknown> {
  data?: T;
  error?: string;
  message?: string;
}
